<?php

// fichier de langues en chinois

//Index
define("_ACCUEIL","主页");
define("_BIENVENUE","欢迎访问BTG (Better Than Google), 基于概念引用(非单词引用)的多语种语义搜索引擎。");
define("_PROMOTION","在未来几周里，这将成为在互联网上使用最多的革命性搜索引擎");
define("_MORE_INFO","更多信息");

//Header
define("_RECHERCHER","搜索");
define("_ARTICLES","文章");
define("_ARTICLES_NEW","新文章");
define("_ONTO_NEW","新的术语");
define("_MAINTENANCE","维护");

//Footer
define("_WHY","BTG由萨瓦大学三年级计算机系实现");
define("_FULL_CODE_1","你可以通过以下链接在GitHub上获取全部代码");
define("_FULL_CODE_2","链接");
define("_ICON","图标来自");
define("_FROM","从");
define("_VECTOR","Vector图片由");

//tableShowByID
define("_REFERENCE","引用:");

?>
