<?php
 
// fichier de langues en anglais

//Index
define("_ACCUEIL","Accueil");
define("_BIENVENUE","Welcome on the website of our project BTG (Better Than Google), a multilingual semantics search engine multilingue based on the referencings of concepts rather than words.");
define("_PROMOTION","Discover the revolutionary search engine who will be the most used of the internet in a couple of weeks...");
define("_MORE_INFO","More informations");

//Header
define("_RECHERCHER","Search");
define("_ARTICLES","Articles");
define("_ARTICLES_NEW","New article");
define("_ONTO_NEW","New ontoterminology");
define("_MAINTENANCE","Maintenance");

//Footer
define("_WHY","BTG is a project realised as a part of our third year of computer science license.");
define("_FULL_CODE_1","The entire code is avaible on GitHub at ");
define("_FULL_CODE_2","this adress");
define("_ICON","Icon made by");
define("_FROM","from");
define("_VECTOR","Vector images by");

//tableShowByID
define("_REFERENCE","References:");

?>