<?php
 
// fichier de langues en français

//Index
define("_ACCUEIL","Accueil");
define("_BIENVENUE","Bienvenue sur le site de notre projet BTG (Better Than Google), un moteur de recherche sémantique multilingue basé sur les référencements de concepts et non de mots.");
define("_PROMOTION","Découvrez le moteur de recherche révolutionnaire qui deviendra le plus utilisé de l'Internet d'ici quelques semaines...");
define("_MORE_INFO","Plus d'infos");

//Header
define("_RECHERCHER","Rechercher");
define("_ARTICLES","Articles");
define("_ARTICLES_NEW","Nouvel article");
define("_ONTO_NEW","Nouvelle ontoterminologie");
define("_MAINTENANCE","Maintenance");

//Footer
define("_WHY","BTG est un projet réalisé dans le cadre de la L3 Informatique.");
define("_FULL_CODE_1","Le code complet est disponible sur GitHub à ");
define("_FULL_CODE_2","cette adresse");
define("_ICON","Icône fait par");
define("_FROM","de");
define("_VECTOR","Vector images par");

//tableShowByID
define("_REFERENCE","Références:");

?>